[package]
name = "rumtk-hl7-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = "0.11.2"
phf_macros = "0.11.2"
chrono = "0.4.38"
unicode-segmentation = "1.10.1"
rumtk-core = { path = "../rumtk-core" }
